proyecto_contador_2/proyecto_contador_2/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tenant_app.urls'), name='tenant_app'),
    path('', include('django.contrib.auth.urls')),
]

proyecto_contador_2/tenant_app/urls.py
from django.contrib import admin
from django.urls import path, include
from tenant_app import views

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('sign-up', views.sign_up, name='sign_up'),
    path('lista/', views.TrabajadorList, name='lista'),
    path('lista-liquidacion/<int:id>/', views.LiquidacionList, name='lista-liquidacion'),
    path('lista-liquidaciones/', views.LiquidacionesList, name='lista-liquidaciones'),
    path('nuevo-trabajador/', views.nuevo_trabajador, name='nuevo-trabajador'),
    path('eliminar-trabajador/<int:id>', views.eliminarTrabajadores, name='eliminar-trabajador'),
    path('trabajador/<int:id>', views.detalle_trabajador, name='trabajador'),
    path('nueva-liquidacion/<int:id>', views.nueva_liquidacion, name='nueva-liquidacion'),
    path('datos-liquidacion/<int:id>', views.datos_liquidacion, name= 'datos-liquidacion'),
    path('pdf/<int:id>', views.liquidacion, name='pdf'),
]

proyecto_contador_2/tenant_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import inlineformset_factory
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Div
from django.core.validators import *
from tenant_app.models import *
from tenant_app.listas import *

class DateInput(forms.DateInput):
    input_type = 'date'

class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ["username", "email","password1", "password2"]

class Datos_EmpleadoForm(forms.ModelForm):
    Rut = forms.CharField(validators=[MinLengthValidator(9, 'Debe tener 9 digitos y con guion'), MaxLengthValidator(9, 'Debe tener 9 digitos y con guion')], required=True)
    Nombres = forms.CharField(validators=[MinLengthValidator(3, 'Minimo de caracteres 3'), MaxLengthValidator(100, 'Maximo de caracteres 100')], required=True)
    Apellidos = forms.CharField(validators=[MinLengthValidator(3, 'Minimo de caracteres 3'), MaxLengthValidator(100, 'Maximo de caracteres 100')], required=True)
    Direccion = forms.CharField(validators=[MinLengthValidator(5, 'Minimo de caracteres 5'), MaxLengthValidator(100, 'Maximo de caracteres 100')], required=True)
    Comuna = forms.ChoiceField(choices=Comunas, required=True)
    Fecha_Nacimiento = forms.DateField(widget=DateInput)
    Sexo = forms.ChoiceField(required=True, choices=sex_choices)
    Estado_civil = forms.ChoiceField(required=True, choices=civil_status_choices)
    Nacionalidad = forms.ChoiceField(required=True,choices=Nacionalidades)
    Numero_De_Pasaporte = forms.CharField(validators=[MinLengthValidator(3, 'Minimo de caracteres 3'), MaxLengthValidator(100, 'Maximo de caracteres 100')], required=False)
    Celular = forms.CharField(validators=[MinLengthValidator(9, 'Debe ser en el siguiente formato 91111111'), MaxLengthValidator(9, 'Debe ser en el siguiente formato 91111111')], required=True)
    Email = forms.EmailField(required=True)
    Pensionado_por_Invalidez = forms.BooleanField(required=False)
    Profesional = forms.BooleanField(required=False)
    Tipo_de_impuesto_unico = forms.ChoiceField(required=True, choices=taxes_choices)
    Descuento_Prestamo_SII = forms.BooleanField(required=False)
    Tecnico_Extranjero = forms.BooleanField(required=False)
 
    class Meta:
        model = Datos_Empleado
        fields = [
            'Rut',
            'Nombres',
            'Apellidos',
            'Direccion',
            'Comuna',
            'Fecha_Nacimiento',
            'Sexo',
            'Estado_civil',
            'Nacionalidad',
            'Numero_De_Pasaporte',
            'Celular',
            'Email',
            'Pensionado_por_Invalidez',
            'Profesional',
            'Tipo_de_impuesto_unico',
            'Descuento_Prestamo_SII',
            'Tecnico_Extranjero',
            ]
        
    def clean_comuna(self):
        Comuna = self.cleaned_data.get('Comuna')
        if Comunas in Comuna:
            return Comuna
        else:
            raise forms.ValidationError('Error en select')
        
    def clean_sexo(self):
        Sexo = self.cleaned_data.get('Sexo')
        if sex_choices in Sexo:
            return Sexo
        else:
            raise forms.ValidationError('Error en select')
        
    def clean_estado_civil(self):
        Estado_civil = self.cleaned_data.get('Estado_civil')
        if civil_status_choices in Estado_civil:
            return Estado_civil
        else: 
            raise forms.ValidationError('Error en select')

    def clean_nacionalidad(self):
        Nacionalidad = self.cleaned_data.get('Nacionalidad')
        if Nacionalidades in Nacionalidad:
            return Nacionalidad
        else: 
            raise forms.ValidationError('Error en select')
        
    def clean_tipo_de_impuesto_unico(self):
        Tipo_de_impuesto_unico = self.cleaned_data.get('Tipo_de_impuesto_unico')
        if taxes_choices in Tipo_de_impuesto_unico:
            return Tipo_de_impuesto_unico
        else:
            raise forms.ValidationError('Error en select')

class RegimenForm(forms.ModelForm):
    Regimen_Provisional = forms.ChoiceField(choices=regimen)
    #AFP
    Afp = forms.ChoiceField(choices=afp)
    Ahorro_imponible = forms.DecimalField(validators=[MinValueValidator(0)], required=False)
    Ahorro_Voluntario_Afp = forms.DecimalField(validators=[MinValueValidator(0)], required=False)
    Desea_APV = forms.BooleanField(required=False, initial=False)
    #IPS 
    Ex_caja = forms.ChoiceField(choices=ex_caja, required=False)
    Tasa_Ex_caja = forms.DecimalField(validators=[MinValueValidator(0)], required=False)

    class Meta:
        model = Regimen_Provisional
        fields = [
            'Regimen_Provisional',
            'Afp',
            'Ahorro_imponible',
            'Ahorro_Voluntario_Afp',
            'Desea_APV',
            'Ex_caja',
            'Tasa_Ex_caja',
        ]

    def clean_regimen_provisional(self):
        Regimen_Provisional = self.cleaned_data.get('Regimen_Provisional')
        if regimen in Regimen_Provisional:
            return Regimen_Provisional
        else:
            raise forms.ValidationError('Error en select')
        
    def clean_afp(self):
        Afp = self.cleaned_data.get('Afp')
        if afp in Afp:
            return Afp
        else:
            raise forms.ValidationError('Error en select')
        
    def clean_ex_caja(self):
        Ex_caja = self.cleaned_data.get('Ex_caja')
        if ex_caja in Ex_caja:
            return ex_caja
        else:
            raise forms.ValidationError('Error en select')

class ApvForm(forms.ModelForm):
    Institucion_Apv = forms.ChoiceField(choices=lista_institucion_apv)
    Nro_Contrato_Apv = forms.CharField(required=False)
    Forma_Pago_Apv = forms.ChoiceField(choices=pago_apv)
    Regimen_Apv = forms.ChoiceField(choices=regimen_apv)
    Ahorro_Pesos = forms.DecimalField(validators=[MinValueValidator(0)], required=False)
    Ahorro_UF = forms.DecimalField(validators=[MinValueValidator(0)], required=False)
    Deposito_Convenido = forms.DecimalField(validators=[MinValueValidator(0)], required=False)
    
    class Meta:
        model = APV
        fields = [
            'Institucion_Apv',
            'Nro_Contrato_Apv',
            'Forma_Pago_Apv',
            'Regimen_Apv',
            'Ahorro_Pesos',
            'Ahorro_UF',
            'Deposito_Convenido',
        ]

    def clean_institucion_apv(self):
        Institucion_Apv = self.cleaned_data.get('Institucion_Apv')
        if lista_institucion_apv in Institucion_Apv:
            return Institucion_Apv
        else:
            raise forms.ValidationError('Error en select')
        
    def clean_forma_pago_apv(self):
        Forma_Pago_Apv = self.cleaned_data.get('Forma_Pago_Apv')
        if pago_apv in Forma_Pago_Apv:
            return Forma_Pago_Apv
        else:
            raise forms.ValidationError('Error en select')
        
    def clean_regimen_apv(self):
        Regimen_Apv = self.cleaned_data.get('Regimen_Apv')
        if regimen_apv in Regimen_Apv:
            return Regimen_Apv
        else:
            raise forms.ValidationError('Error en select')

class SaludForm(forms.ModelForm):
    Institucion_Salud = forms.ChoiceField(choices=institucion_salud)
    Plan_UF = forms.DecimalField(validators=[MinValueValidator(0)], required=False)

    class Meta:
        model = Salud
        fields = [
            'Institucion_Salud',
            'Plan_UF',
        ]

    def clean_institucion_salud(self):
        Institucion_Salud = self.cleaned_data.get('Institucion_Salud')
        if institucion_salud in Institucion_Salud:
            return Institucion_Salud
        else:
            raise forms.ValidationError('Error en select')

class LiquidacionForm(forms.ModelForm):
    #Liquidacion
    Fecha_Emision = forms.DateField(widget=DateInput)
    Profesion = forms.CharField(validators=[MinLengthValidator(3, 'Minimo de caracteres 3'), MaxLengthValidator(100, 'Maximo de caracteres 100')], required=False)
    Tipo_Trabajador = forms.ChoiceField(choices=tipo_trabajador)
    Sin_Seguro_Cesantia = forms.BooleanField(required=False)
    Trabajador_Agricola = forms.BooleanField(required=False)
    Director_de_Empresa = forms.BooleanField(required=False)
    Sueldo_Base = forms.DecimalField(validators=[MinValueValidator(0)])
    Tipo_Contrato = forms.ChoiceField(choices=duracion_contrato)
    Tipo_Jornada_Trabajo = forms.ChoiceField(choices=work_choices)
    Dias_Descontados = forms.IntegerField(validators=[MinValueValidator(0)])
    Dias_Licencia = forms.IntegerField(validators=[MinValueValidator(0)])

    class Meta:
        model = Liquidacion
        fields = [
            'Fecha_Emision',
            'Profesion',
            'Tipo_Trabajador',
            'Sin_Seguro_Cesantia',
            'Trabajador_Agricola',
            'Director_de_Empresa',
            'Sueldo_Base',
            'Tipo_Contrato',
            'Tipo_Jornada_Trabajo',
            'Dias_Descontados',
            'Dias_Licencia',
        ]

    def clean_tipo_trabajador(self):
        Tipo_Trabajador = self.cleaned_data.get('Tipo_Trabajador')
        if tipo_trabajador in Tipo_Trabajador:
            return Tipo_Trabajador
        else:
            raise forms.ValidationError('Error en select')
    
    def clean_tipo_contrato(self):
        Tipo_Contrato = self.cleaned_data.get('Tipo_Contrato')
        if duracion_contrato in Tipo_Contrato:
            return Tipo_Contrato
        else:
            raise forms.ValidationError('Error en select')
        
    def clean_jornada_trabajo(self):
        Tipo_Jornada_Trabajo = self.cleaned_data.get('Tipo_Jornada_Trabajo')
        if work_choices in Tipo_Jornada_Trabajo:
            return Tipo_Jornada_Trabajo
        else:
            raise forms.ValidationError('Error en select')

proyecto_contador_2/templates/main/base.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
        <title>{% block title %}Remuneracion{% endblock %}</title>
    <body>
        {% load has_group %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                {% if user|has_group:'admin' %}
                <div>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="/home">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/lista/">Trabajadores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/lista-liquidaciones">Liquidaciones</a>
                        </li>
                    </ul>
                </div>
                {% else %}
                <div>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="/home">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/lista-liquidaciones">Liquidaciones</a>
                        </li>
                    </ul>
                </div>
                {% endif %}
                <div>
                    <ul class="navbar-nav">
                        {% if user.is_authenticated %}
                        <span class="navbar-text">{{user.username}} | </span>
                        <li class="nav-item">
                            <a class="nav-link" href="/logout">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="/login">Login</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

proyecto_contador_2/templates/main/datos_liquidacion.html
{% extends 'main/base.html' %}
{% block title %}Datos de Liquidacion{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    .card {
        margin-top: 20px;
        margin-bottom: 20px;
    }
</style>
&nbsp;
<form method="POST">
    {% csrf_token %}
    <div class="card">
        <div class="card-body">
            <div class="card-title"><h3>Regimen Provisional</h3></div>
            {{form_2.Regimen_Provisional|as_crispy_field}}
            <div id="afp-fields" style="display: none">
                {{ form_2.Afp|as_crispy_field }}
                {{ form_2.Ahorro_imponible|as_crispy_field }}
                {{ form_2.Ahorro_Voluntario_Afp|as_crispy_field }}
                {{ form_2.Desea_APV|as_crispy_field }}
            </div>
            <div id="ips-fields" style="display: none">
                {{ form_2.Ex_caja|as_crispy_field }}
                {{ form_2.Tasa_Ex_caja|as_crispy_field }}
            </div>
        </div>
    </div>
    <div id="apv-fields" style="display: none">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h3>APV</h3>
                </div>
                {{form_3|crispy}}
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="card-title"><h3>Salud</h3></div>
            {{form_4|crispy}}
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="card-title"><h3>No Imponibles</h3></div>
            {{form_5|crispy}}
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="card-title"><h3>Adicionales</h3></div>
            {{form_6|crispy}}
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="card-title"><h3>Descuentos</h3></div>
            {{form_7|crispy}}
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="card-title"><h3>Movimientos personales</h3></div>
            {{form_8|crispy}}
        </div>
    </div>
    <div style="padding-top: 20px; padding-bottom: 20px;">
        <button type="submit" class="btn btn-success">Guardar</button>
    </div> 
</form>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function () {
        var choiceField = $('#id_Regimen_Provisional');
        var checkField = $('#id_Desea_APV');
        var afpFields = $('#afp-fields');
        var ipsFields = $('#ips-fields');
        var apvFields = $('#apv-fields');

        function actualizarCampos() {
            var valorSeleccionado = choiceField.val();
            if (valorSeleccionado == 'AFP') {
                afpFields.show();
                ipsFields.hide();
            } else if (valorSeleccionado == 'IPS (Ex-INP)') {
                afpFields.hide();
                ipsFields.show();
            } else {
                afpFields.hide();
                ipsFields.hide();
            }
        }

        function mostrarAPV() {
            if (checkField.is(':checked')) {
                apvFields.show();
            } else {
                apvFields.hide();
            }  
        }

        actualizarCampos();
        mostrarAPV();
        choiceField.change(actualizarCampos);
        checkField.change(mostrarAPV);
    });

</script>
{% endblock %}

proyecto_contador_2/templates/main/home.html
{% extends 'main/base.html'%}
{% block title %}Inicio{% endblock %}
{% block content %}
<div class="card" style="width: auto; align-items: center; margin: auto; margin-top: 100px;">
    <div class="card-body">
      <h1 class="card-title">Bienvenido</h1>
    </div>
</div>
<div class="card" style="width: auto; align-items: center; margin: auto; margin-top: 10px;">
    <div class="card-body">
      <h1 class="card-title">Sistema de liquidacion de empleados</h1>
    </div>
</div>
{% endblock %}

proyecto_contador_2/templates/main/liquidacion.html
{% extends 'main/base.html' %}
{% block title %}Nueva Liquidacion{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
&nbsp;
<form method="POST">
    {% csrf_token %}
    <h3>Datos Basicos</h3>
    {{form_1|crispy}}
    <button type="submit" class="btn btn-success">Guardar</button>
</form>
{% endblock %}

proyecto_contador_2/templates/main/lista.html
{% extends 'main/base.html' %}
{% block title %}Trabajadores{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
&nbsp;
<div class="container-fluid">
<div style="margin: auto; margin-bottom: 10px; width: auto;">
    <a href="/nuevo-trabajador" class="btn btn-info" role="button">Nuevo trabajador</a>
</div> 
<table class="table table-striped table-inverse table-responsive table-bordered">
    <thead class="thead-inverse">
        <tr>
            <th>Rut</th>
            <th>Nombres</th>
            <th>Apellidos</th>
            <th>Direccion</th>
            <th>Comuna</th>
            <th>Nacionalidad</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
        {% for trabajador in trabajadores %}
        <tr>
            <th>{{trabajador.Rut}}</th>
            <th>{{trabajador.Nombres}}</th>
            <th>{{trabajador.Apellidos}}</th>
            <th>{{trabajador.Direccion}}</th>
            <th>{{trabajador.Comuna}}</th>
            <th>{{trabajador.Nacionalidad}}</th>
            <th>
                <a href="/lista-liquidacion/{{trabajador.id}}" class="btn btn-info btn-sm"><i class="bi bi-clipboard""></i></a>
                <a href="/trabajador/{{trabajador.id}}" class="btn btn-success btn-sm"><i class="bi bi-pencil"></i></a>
                <a href="/eliminar-trabajador/{{trabajador.id}}" class="btn btn-danger btn-sm"><i class="bi bi-trash"></i></a>
            </th>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock %}

proyecto_contador_2/templates/main/lista_liquidaciones.html
{% extends 'main/base.html' %}
{% block title %}Liquidaciones{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
&nbsp;
<div class="container-fluid">
<div style="margin: auto; margin-bottom: 10px; width: auto;">
    <a href="/nueva-liquidacion/{{object.id}}" class="btn btn-info" role="button">Nueva liquidacion</a>
</div> 
<table class="table table-striped table-inverse table-responsive table-bordered">
    <thead class="thead-inverse">
        <tr>
            <th>Fecha de emision</th>
            <th>Tipo de trabajador</th>
            <th>Seguro de cesantia</th>
            <th>Trabajador agricola</th>
            <th>Director de empresa</th>
            <th>Sueldo base</th>
            <th>Tipo de contrato</th>
            <th>Tipo de jornada de trabajo</th>
            <th>Dias descontados</th>
            <th>Dias Licencia</th>
            <th>Cargas familiares</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
        {% for liquidacion in liquidaciones %}
        <tr>
            <th>{{liquidacion.Fecha_Emision}}</th>
            <th>{{liquidacion.Tipo_Trabajador}}</th>
            <th>{{liquidacion.Sin_Seguro_Cesantia|yesno:"Si,No"}}</th>
            <th>{{liquidacion.Trabajador_Agricola|yesno:"Si,No"}}</th>
            <th>{{liquidacion.Director_de_Empresa|yesno:"Si,No"}}</th>
            <th>{{liquidacion.Sueldo_Base}}</th>
            <th>{{liquidacion.Tipo_Contrato}}</th>
            <th>{{liquidacion.Tipo_Jornada_Trabajo}}</th>
            <th>{{liquidacion.Dias_Descontados}}</th>
            <th>{{liquidacion.Dias_Licencia}}</th>
            <th>{{liquidacion.Cargas_Familiares}}</th>
            <th>
                <a href="/datos-liquidacion/{{liquidacion.id}}" class="btn btn-info btn-sm"><i class="bi bi-pencil"></i></a>
                <a href="/pdf/{{liquidacion.id}}" class="btn btn-success btn-sm"><i class="bi bi-filetype-pdf"></i></a>
            </th>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock %}

proyecto_contador_2/templates/main/lista_liquidaciones_total.html
{% extends 'main/base.html' %}
{% block title %}Liquidaciones{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
&nbsp;
<div class="container-fluid">
{% load has_group %}

<table class="table table-striped table-inverse table-responsive table-bordered">
    <thead class="thead-inverse">
        <tr>
            <th>Fecha de emision</th>
            <th>Tipo de trabajador</th>
            <th>Seguro de cesantia</th>
            <th>Trabajador agricola</th>
            <th>Director de empresa</th>
            <th>Sueldo base</th>
            <th>Tipo de contrato</th>
            <th>Tipo de jornada de trabajo</th>
            <th>Dias descontados</th>
            <th>Dias Licencia</th>
            <th>Cargas familiares</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
        {% for liquidacion in liquidaciones %}
        <tr>
            <th>{{liquidacion.Fecha_Emision}}</th>
            <th>{{liquidacion.Tipo_Trabajador}}</th>
            <th>{{liquidacion.Sin_Seguro_Cesantia|yesno:"Si,No"}}</th>
            <th>{{liquidacion.Trabajador_Agricola|yesno:"Si,No"}}</th>
            <th>{{liquidacion.Director_de_Empresa|yesno:"Si,No"}}</th>
            <th>{{liquidacion.Sueldo_Base}}</th>
            <th>{{liquidacion.Tipo_Contrato}}</th>
            <th>{{liquidacion.Tipo_Jornada_Trabajo}}</th>
            <th>{{liquidacion.Dias_Descontados}}</th>
            <th>{{liquidacion.Dias_Licencia}}</th>
            <th>{{liquidacion.Cargas_Familiares}}</th>
            <th>
                {% if user|has_group:'admin' %}
                <a href="/datos-liquidacion/{{liquidacion.id}}" class="btn btn-info btn-sm"><i class="bi bi-pencil"></i></a>
                <a href="/pdf/{{liquidacion.id}}" class="btn btn-success btn-sm"><i class="bi bi-filetype-pdf"></i></a>
                {% else %}
                <a href="/pdf/{{liquidacion.id}}" class="btn btn-success btn-sm"><i class="bi bi-filetype-pdf"></i></a>
                {% endif %}
            </th>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock %}

proyecto_contador_2/templates/main/nuevo_trabajador.html
{% extends 'main/base.html' %}
{% block title %}Nuevo tranajador{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    .card {
        margin-top: 20px;
        margin-bottom: 20px;
    }
</style>
&nbsp;
<form method="POST">
    {% csrf_token %}
    <div class="card">
        <div class="card-body">
            <div class="card-title"><h3>Datos Basicos</h3></div>
            {{form|crispy}}
        </div>
    </div>
    <div style="padding-top: 20px; padding-bottom: 20px;">
        <button type="submit" class="btn btn-success">Añadir</button>
    </div> 
</form>
{% endblock %}

proyecto_contador_2/templates/main/trabajador.html
{% extends 'main/base.html' %}
{% block title %}Trabajadores{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    .card {
        margin-top: 20px;
        margin-bottom: 20px;
    }
</style>
&nbsp;
<form method="POST">
    <div class="container-fluid">
        {% csrf_token %}
        <h1>{{total}}</h1>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Datos Personales</h5>
                {{card|crispy}}
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Forma de pago</h5>
                {{card_7|crispy}}
            </div>
        </div>
        <div style="padding-top: 20px; padding-bottom: 20px;">
            <button type="submit" class="btn btn-success">Guardar</button>
        </div>
    </div>
</form>
{% endblock %}

proyecto_contador_2/templates/main/trabajadores.html
{% extends 'main/base.html' %}
{% block title %}Trabajadores{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container-fluid">
<a href="/nuevo-trabajador" class="btn btn-info" role="button">Nuevo trabajador</a>
<table class="table table-striped table-inverse table-responsive">
    <thead class="thead-inverse">
        <tr>
            <th>Rut</th>
            <th>Nombres</th>
            <th>Apellidos</th>
            <th>Direccion</th>
            <th>Comuna</th>
            <th>Nacionalidad</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
        {% for trabajador in trabajadores %}
        <tr>
            <th>{{trabajador.Rut}}</th>
            <th>{{trabajador.Nombres}}</th>
            <th>{{trabajador.Apellidos}}</th>
            <th>{{trabajador.Direccion}}</th>
            <th>{{trabajador.Comuna}}</th>
            <th>{{trabajador.Nacionalidad}}</th>
            <th><a href="/actualizar-trabajador/{{trabajador.id}}" class="btn btn-success btn-sm"><i class="bi bi-pencil"></i></a></th>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock %}